# Generated by Django 2.1.2 on 2020-07-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20180916_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
